
```{r}

source("baseline.R")

```

```{r}

list_of_metadata_file_names <- list.files(source_file_path)
list_of_regions             <- tstrsplit(list_of_metadata_file_names, ".rds", fixed=TRUE)[[1]]

```


```{r}

table_of_number_of_each_celltype <- c()

for (metadata_file_name in list_of_metadata_file_names){
  
  current_metadata_file <- readRDS(paste0(source_file_path, metadata_file_name))
  cell_type_frequency   <- as.list(table(current_metadata_file$cluster_id))
  
  # name_vector <- c()
  # 
  # print(names(cell_type_frequency))
  # 
  # for (cell in names(cell_type_frequency)){
  #   
  #   name_vector <- c(name_vector, rename_list[[cell]])
  #   
  # }
  # 
  # names(cell_type_frequency) <- name_vector
  remaining <- setdiff(unlist(rename_list), names(cell_type_frequency))
  
  for (rem in remaining){
    
    cell_type_frequency[[rem]] <- list()
    
  }
    
  data_df <- as.data.frame(lapply(cell_type_frequency, function(x) if (length(x) == 0) NA else x))
  data_df[is.na(data_df)] <- 0
  data_df <- data_df[, order(names(data_df))]

  table_of_number_of_each_celltype <- rbind(table_of_number_of_each_celltype,
                                            c(data_df))
  
}

rownames(table_of_number_of_each_celltype) <- list_of_regions
df           <- as.data.frame(table_of_number_of_each_celltype)
rownames(df) <- tstrsplit(rownames(df), "_")[[1]]

```

```{r}

studies_to_keep_threshold <- list()

cell_count_thresholds <- c(50, 100, 150, 200, 250, 400)

for (counts in cell_count_thresholds){
  
  studies_to_keep <- list()

  for (cell in colnames(df)){
  
    studies_to_keep[[cell]] <- rownames(df[df[, cell] > counts, ])
  
  }
  
  studies_to_keep_threshold[[as.character(counts)]] <- studies_to_keep
    
}

saveRDS(studies_to_keep_threshold, "interm/studies_to_keep_threshold.rds")

```


```{r}

write.xlsx(as.data.frame(df), "results/Supplementary Table 2B - postQC.xlsx", rowNames=TRUE)

```

