
```{r}

source("baseline.R")

```


```{r}

agg_matrices <- list.files("source/agg_matrix_RN011/")

gene_list <- list()

for (agg in agg_matrices){

  current_agg <- readRDS(paste0("source/agg_matrix_RN011/", agg))
  gene_list[[agg]] <- rownames(current_agg)

}

common_genes <- Reduce(intersect, gene_list)
saveRDS(common_genes, "interm/common_genes_agg_RN011.rds")

```


```{r}

agg_matrices <- list.files("source/agg_matrix_RN011/")
common_genes <- readRDS("interm/common_genes_agg_RN011.rds")

full_matrix <- c()
all_sample_cell_types <- c()

for (agg in agg_matrices){
  
  current_agg        <- readRDS(paste0("source/agg_matrix_RN011/", agg))
  current_cell_names <- tstrsplit(colnames(current_agg), "_#", fixed=TRUE)[[1]]
  current_samples    <- tstrsplit(colnames(current_agg), "_#", fixed=TRUE)[[2]]
  
  # if (agg == "MFC_1.rds"){
  #   
  #   current_samples    <- paste(tstrsplit(colnames(current_agg), "_", fixed=TRUE)[[2]],
  #                               tstrsplit(colnames(current_agg), "_", fixed=TRUE)[[3]],
  #                               tstrsplit(colnames(current_agg), "_", fixed=TRUE)[[4]], sep = "_")
  #                               
  #   
  # }else{
  #   
  #   current_samples    <- tstrsplit(colnames(current_agg), "_", fixed=TRUE)[[2]]
  #   
  # }
  # 
  # new_cell_names <- c()
  # for (cell in current_cell_names){
  #   
  #   new_cell_names <- c(new_cell_names, rename_list[[cell]])
  #   
  # }
  
  region                <- tstrsplit(agg, "_1.rds", fixed=TRUE)[[1]]
  
  final_columns         <- paste0(current_cell_names, "_#", current_samples, "_", rep(region, length(current_samples)))
  colnames(current_agg) <- final_columns
  
  full_matrix           <- cbind(full_matrix, current_agg[common_genes, ])
  #all_sample_cell_types <- c(all_sample_cell_types, new_cell_names)
  
}

```


```{r}

saveRDS(full_matrix, "interm/heatmap_matrix_RN011.rds")

```



```{r}

meta_file_path <- "source/QC_metadata_RN011/"
meta_files     <- list.files(meta_file_path)

all_metadata  <- c()

meta_files <- meta_files[meta_files %in% c("MTG_1.rds", "MTGA_1.rds") == FALSE]

for (file in meta_files){
  
  current_file <- readRDS(paste0(meta_file_path, file))
  current_file <- current_file[, c("cluster_id", "sample_id", "human_age", "sex")]
  df_metadata  <- current_file[!duplicated(current_file), ]
  
  rownames(df_metadata) <- paste0(df_metadata$cluster_id, "_", 
                                  #tstrsplit(df_metadata$sample_id, "_")[[1]], "_",
                                  df_metadata$sample_id, "_",
                                  tstrsplit(file, ".rds")[[1]])

  
  df_metadata$region <- tstrsplit(file, "_1.rds")[[1]]
  
  all_metadata <- rbind(all_metadata, df_metadata)
  
}


```

# IMPORT FILTERED COLUMNS

```{r}

filtered_column_names <- readRDS("interm/final_columns_40_subtype.rds")
full_matrix           <- readRDS("interm/heatmap_matrix_RN011.rds")

colnames(full_matrix) <- paste0(colnames(full_matrix), "_1")
filtered_column_names <- paste0(filtered_column_names, "_1")

filtered_count_matrix <- full_matrix[, colnames(full_matrix) %in% filtered_column_names]
filtered_metadata     <- all_metadata[filtered_column_names, ]

# Ensure row orders match between gene expression and metadata
all(sort(colnames(filtered_count_matrix)) == sort(rownames(filtered_metadata)))

```


```{r}

saveRDS(filtered_count_matrix, "interm/sample_wise40_count_matrix_RAW_RN011.rds")
saveRDS(filtered_metadata,     "interm/sample_wise40_pseudobulk_all_metadata_RN011.rds")

```

```{r}

colData <- data.frame(
  sampleCondition = factor(rep("condition1", length(colnames(filtered_count_matrix)))) # Assuming 10 samples
  )

DESeq2_data  <- DESeq2_normalization(filtered_count_matrix, colData = colData)

#table(apply(filtered_DESeq_matrix, 1, mean))

saveRDS(DESeq2_data[[1]], "source/DESeq2_normalized_counts.rds")
saveRDS(DESeq2_data[[2]], "source/dds.rds")


```


