```{r}

source("baseline.R")

```



```{r}

df_pct   <- readRDS("source/all_pct_metrics_RN012.rds")
agg_mat  <- readRDS("interm/agg_mat_DESeq2_normalized_counts.rds")

library(tidyr)
library(dplyr)

# Step 1: Convert agg_mat to a data frame with genes as a column
agg_df <- as.data.frame(agg_mat)
agg_df$gene <- rownames(agg_mat)

# Step 2: Pivot longer: from wide to long format
agg_long <- agg_df %>%
  pivot_longer(
    cols = -gene,
    names_to = "celltype_region",
    values_to = "agg_expr"
  )

# Step 3: Separate "celltype_region" into "cluster" and "region"
agg_long <- agg_long %>%
  separate(celltype_region, into = c("cluster", "region"), sep = "_")

# Step 4: Join with df_pct by gene + cluster + region
merged_df <- df_pct %>%
  inner_join(agg_long, by = c("gene", "cluster", "region"))

saveRDS(merged_df, "../Figure 2 - Putative Marker Facts/source/normalized_cell_region_expression.rds")

library(dplyr)

# Assuming merged_df has columns: gene, cluster, region, pct1, pct2, agg_expr

cor_by_group <- merged_df %>%
  group_by(region, cluster) %>%
  summarize(
    cor_pct1_agg = cor(pct1, agg_expr, use = "complete.obs"),
    cor_pct2_agg = cor(pct2, agg_expr, use = "complete.obs"),
    cor_pct1_pct2 = cor(pct1, pct2, use = "complete.obs"),
    .groups = "drop"
  )


df <- as.data.frame(cbind(rep(cor_by_group$region, 3), rep(cor_by_group$cluster, 3), 
                          c(cor_by_group$cor_pct1_agg, cor_by_group$cor_pct2_agg, cor_by_group$cor_pct1_pct2), 
                          c(rep("cor_pct1_agg", 85), rep("cor_pct2_agg", 85), rep("cor_pct1_pct2", 85))))

colnames(df) <- c("Region", "Cell", "Cor", "Type")
df$Cor <- as.numeric(df$Cor)

p <- ggplot(data = df, aes(x = Type, y = Cor, fill = Type)) + geom_violin() + theme_classic() +
  theme(axis.text.x = element_text(size = 15), 
        axis.text.y = element_text(size = 15),
        axis.text.x.bottom = element_text(size = 8),
        axis.text.y.left = element_text(size = 8),
        legend.position="none"
        ) +
        xlab("Correlation Type") +
        ylab("Correlation value") 

p

# ggsave(filename = "figures/pct1_pct2_expression_correlation_violin.png", plot = p, width = 1440, height = 1200, units = "px", device = "png")
plot_mean_data <- df %>% group_by(Type) %>% summarise(mean_cor = mean(Cor, na.rm = TRUE))

```

```{r}

df$Type <- as.factor(df$Type)

p <- ggplot(df, aes(x=Type, y=Cor))                                                                                         +
ggdist::stat_halfeye(aes(fill=Type), adjust = .5, width = 0.55, .width = 0, justification = -.3, point_interval = NULL) +
geom_point(aes(color=Region), size = 1.5, alpha = .2, position = position_jitter(seed = 1, width = .1))                +         
geom_point(data = plot_mean_data,   aes(x = Type, y = mean_cor), color = "black", size = 6, shape = 18)                +
  #xlab("")                                             +
ylab("")                                             +
theme_bw()                                           +
theme(axis.text.y  = element_text(size = 20),
     axis.text.x  = element_blank(),
     axis.ticks.y = element_blank(),
     axis.ticks.x = element_blank(),
     plot.title = element_text(hjust = 0.5),
     legend.position = "none")                                                         +
scale_fill_manual(values = c(
  cor_pct1_agg  = "#0fbabd",
  cor_pct2_agg  = "skyblue",
  cor_pct1_pct2 = "cornflowerblue"   # lighter alternative to "darkblue"
))                 
#scale_color_gradient(low = "blue", high = "red")                                        

ggsave(filename = "figures/pct1_pct2_expression_correlation_raincloud.png", plot = p, width = 1440, height = 1200, units = "px", device = "png")
```

```{r}

df_corr <- df %>% group_by(Cell, Type) %>% summarise(mean_metric = mean(Cor), sd_metric = sd(Cor))


```


```{r}

ggplot(df, aes(x=DEG, y=Cor))                                                                        +
ggdist::stat_halfeye(aes(fill=DEG), adjust = .5, width = 0.55, .width = 0, justification = -.3, point_interval = NULL)   +
geom_point(aes(color=Expression), size = 1.5, alpha = .2, position = position_jitter(seed = 1, width = .1))              +
geom_point(data = plot_mean_data,   aes(x = DEG, y = mean_value), color = "black", size = 6, shape = 18)                 +
xlab("")                                             +
ylab("")                                             +
theme_bw()                                           +
theme(axis.text.y  = element_text(),
     axis.text.x  = element_blank(),
     axis.ticks.y = element_blank(),
     axis.ticks.x = element_blank(),
     plot.title = element_text(hjust = 0.5),
     legend.position = "none")                                                         +
#add_pvalue(plot_stat.test_DEG, label = "{p.signif}", label.size = 6, tip.length = 0.01) +
scale_fill_manual(values = c("DEG"="#0fbabd", "background"="skyblue"))                  +
scale_color_gradient(low = "blue", high = "red")                                        +
guides(fill=guide_legend(title="Type of Gene"))                                         +
scale_y_continuous(limits = c(0, 1.2), breaks = breaks)           

```


