```{r}

source("baseline.R")

validation_metrics <- readRDS("source/combined_validation_results_RN012.rds")

colnames(validation_metrics) <- c("study", "canonical_accuracy", "canonical_F1", "putative_accuracy", "putative_F1", "canonical_ari", 
                                  "putative_ari")

```


```{r}

putative                 <- validation_metrics[, c("study", "putative_ari")]
putative$set_type        <- "putative"
colnames(putative)[1:2]  <- c("study", "ARI")
canonical                <- validation_metrics[, c("study", "canonical_ari")]
canonical$set_type       <- "canonical"
colnames(canonical)[1:2] <- c("study", "ARI")

ARI_plot_data      <- rbind(putative, canonical)


p <- ggplot(ARI_plot_data, aes(study, ARI, fill = set_type)) + geom_bar(stat="identity", position = "dodge", width=0.65) +  
                                                                    labs(title="Multiple Bar plots")                    +
                                                                    scale_fill_manual(values = c("#4682B4", "#4BB446")) +
                                                                    xlab("Cortical Region") + ylab("Leave-One-Out Adjusted Rand Index") +
                                                                    theme_bw()                                          +
                                                                    theme(axis.text.x = element_text(angle = 45, size = 20, hjust = 1),
                                                                          axis.text.y = element_text(size = 20), 
                                                                          axis.title.x = element_text(size = 20),
                                                                          axis.title.y = element_text(size = 20))
p
ggsave(filename = "figures/Figure - 3A - LOO-ARI scores.png", plot = p, device = "png", width = 4000, height = 2100, units = "px")

wilcox.test(ARI ~ set_type, data = ARI_plot_data)


p <- ggplot(data = ARI_plot_data, aes(x = set_type, y = ARI, fill = set_type)) + geom_violin() + 
  theme_classic() +
  ylim(c(0, 1))   +
  scale_fill_manual(values = c("#4682B4", "#4BB446")) + 
  theme(axis.text.x = element_blank(), 
        axis.text.y = element_text(size = 20),
        axis.title.x = element_blank(), 
        axis.title.y = element_text(size = 20), 
        legend.position = "none")

ggsave(filename = "figures/Figure - 3 ARI - violin.png", plot = p, device = "png", width = 2000, height = 2100, units = "px")


```


```{r}

putative                 <- validation_metrics[, c("study", "putative_accuracy")]
putative$set_type        <- "putative"
colnames(putative)[1:2]  <- c("study", "accuracy")
canonical                <- validation_metrics[, c("study", "canonical_accuracy")]
canonical$set_type       <- "canonical"
colnames(canonical)[1:2] <- c("study", "accuracy")

ARI_plot_data      <- rbind(putative, canonical)


p <- ggplot(ARI_plot_data, aes(study, accuracy, fill = set_type)) + geom_bar(stat="identity", position = "dodge", width=0.65) +  
                                                                    labs(title="Multiple Bar plots")                    +
                                                                    scale_fill_manual(values = c("#4682B4", "#4BB446")) +
                                                                    xlab("Cortical Region") + ylab("Leave-One-Out Accuracy") +
                                                                    theme_bw()                                          +
                                                                    theme(axis.text.x = element_text(angle = 45, size = 20, hjust = 1),
                                                                          axis.text.y = element_text(size = 20), 
                                                                          axis.title.x = element_text(size = 20),
                                                                          axis.title.y = element_text(size = 20))
p
ggsave(filename = "figures/Figure - 3B - LOO-accuracy scores.png", plot = p, device = "png", width = 4000, height = 2100, units = "px")

wilcox.test(accuracy ~ set_type, data = ARI_plot_data)

p <- ggplot(data = ARI_plot_data, aes(x = set_type, y = accuracy, fill = set_type)) + geom_violin() + 
  theme_classic() +
  scale_fill_manual(values = c("#4682B4", "#4BB446")) + 
  theme(axis.text.x = element_blank(), 
        axis.text.y = element_text(size = 20),
        axis.title.x = element_blank(), 
        axis.title.y = element_text(size = 20), 
        legend.position = "none")

ggsave(filename = "figures/Figure - 3 Accuracy - violin.png", plot = p, device = "png", width = 2000, height = 2100, units = "px")


```



```{r}

putative                 <- validation_metrics[, c("study", "putative_F1")]
putative$set_type        <- "putative"
colnames(putative)[1:2]  <- c("study", "F1")
canonical                <- validation_metrics[, c("study", "canonical_F1")]
canonical$set_type       <- "canonical"
colnames(canonical)[1:2] <- c("study", "F1")

ARI_plot_data      <- rbind(putative, canonical)


p <- ggplot(ARI_plot_data, aes(study, F1, fill = set_type)) + geom_bar(stat="identity", position = "dodge", width=0.65) +  
                                                                    labs(title="Multiple Bar plots")                    +
                                                                    scale_fill_manual(values = c("#4682B4", "#4BB446")) +
                                                                    xlab("Cortical Region") + ylab("Leave-One-Out macro F1") +
                                                                    theme_bw()                                          +
                                                                    theme(axis.text.x = element_text(angle = 45, size = 20, hjust = 1),
                                                                          axis.text.y = element_text(size = 20), 
                                                                          axis.title.x = element_text(size = 20),
                                                                          axis.title.y = element_text(size = 20))
p
ggsave(filename = "figures/Figure - 3C - LOO-ARI macro_F1.png", plot = p, device = "png", width = 4000, height = 2100, units = "px")

wilcox.test(F1 ~ set_type, data = ARI_plot_data)


p <- ggplot(data = ARI_plot_data, aes(x = set_type, y = F1, fill = set_type)) + geom_violin() + 
  theme_classic() +
  scale_fill_manual(values = c("#4682B4", "#4BB446")) + 
  theme(axis.text.x = element_blank(), 
        axis.text.y = element_text(size = 20),
        axis.title.x = element_blank(), 
        axis.title.y = element_text(size = 20), 
        legend.position = "none")

ggsave(filename = "figures/Figure - 3 F1 - violin.png", plot = p, device = "png", width = 2000, height = 2100, units = "px")



```

